name: Fetch Packages

on:
  push:
    branches:
      - master  # Change to your desired branch

jobs:
  fetch_packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch Container Packages from GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token for authentication
        run: |
          curl -L \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               "https://api.github.com/orgs/docker-pkg/packages?package_type=container" \
               > packages.json

      - name: Display Packages
        run: |
          cat packages.json  # Display the contents of packages.json for debugging (optional)
