name: Update Packages

on:
  push:
    branches:
      - master

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Container Packages from GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provided token
        run: |
          curl -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/orgs/docker-pack/packages?package_type=container" \
               > packages.json
          
          # Check the contents of packages.json for debugging
          cat packages.json

      - name: Update HTML
        run: python update_html.py packages.json
